In [2]:
import numpy as np
import cv2 as cv

In [3]:
img = cv.imread('jump.png')

len = 640
width = 608

newim = cv.resize(img, (width, len)) #dsize first is len, second is width Q. why insert width and height, not height and width?

cv.imwrite('fixed.png', newim)
fixedim = cv.imread('fixed.png')
print('origin img',img.shape, 'is changed to fixed img', fixedim.shape)# height, width, channel (chanel 3 is color, 1 is black white)


origin img (1985, 1985, 3) is changed to fixed img (640, 608, 3)


In [4]:
#background remover

test = cv.imread('test.png')
print(test)

[[[237 237 237]
  [237 237 237]
  [236 236 236]
  ...
  [237 237 237]
  [237 237 237]
  [237 237 237]]

 [[237 237 237]
  [237 237 237]
  [237 237 237]
  ...
  [237 237 237]
  [237 237 237]
  [237 237 237]]

 [[237 237 237]
  [237 237 237]
  [237 237 237]
  ...
  [237 237 237]
  [237 237 237]
  [237 237 237]]

 ...

 [[238 236 235]
  [238 236 235]
  [238 236 235]
  ...
  [238 236 235]
  [238 236 235]
  [238 236 235]]

 [[238 236 235]
  [238 236 235]
  [238 236 235]
  ...
  [238 236 235]
  [238 236 235]
  [238 236 235]]

 [[238 236 235]
  [238 236 235]
  [238 236 235]
  ...
  [238 236 235]
  [238 236 235]
  [238 236 235]]]
